### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'next' for the generator constructed by _make_data_gen

### ISSUE THREAD

**Issue by wenouyang** [MarvinTeichmann/MediSeg#5]
Hi Marvin,

I run `python train.py` in AP5, and got the following error message

> File "train.py", line 67, in <module>
>     main()
>   File "train.py", line 64, in main
>     train.do_training(hypes)
>   File "/home/FCN/MediSeg/AP5/tensorvision/train.py", line 392, in do_training
>     _start_enqueuing_threads(hypes, q, sess, data_input)
>   File "/home/FCN/MediSeg/AP5/tensorvision/train.py", line 75, in _start_enqueuing_threads
>     sess, hypes['dirs']['data_dir'])
>   File "/home/FCN/MediSeg/AP5/hypes/../model/segmentation_input.py", line 205, in start_enqueuing_threads
>     gen.next()
> AttributeError: 'generator' object has no attribute 'next'
> 
 
It seems to me that the problem comes from the function of 
```
def _make_data_gen(hypes, phase, data_dir):
    Return a data generator that outputs image samples.
``` 
 but I do not figure out the reason. Thanks.

**Comment by MarvinTeichmann** [comment]
Hi wenouyang,

this error is wierd and I have no idea what causis is. Can you have the same error when using the KittiSeg code? In general, I would advise using KittiSeg code, it is the same model but with newer training code.

**Comment by wenouyang** [comment]
Hi Marvin,  this problem comes from the Python version transferring from 2.x to 3.x. After changing it to next(gen), the problem is fixed.  Thanks.

**Comment by MartinThoma** [comment]
See [what is the problem](http://stackoverflow.com/a/1073582/562769) and [how it can be fixed](http://python-future.org/compatible_idioms.html#custom-iterators)

**Comment by MarvinTeichmann** [comment]
@MartinThoma  do you know whether it is possible to use `next(g)` in python 2.7? Might be worse making a habit to to this if it is compatible with both version.

**Comment by MartinThoma** [comment]
@MarvinTeichmann Yes, `next(g)` works for Python 2.7 and for Python 3.X (see https://github.com/MartinThoma/algorithms/blob/master/Python/generator/nextp2p3.py to try it)
